/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddonPeriodHelmSource {
    #[serde(rename = "insecureSkipTLS", skip_serializing_if = "Option::is_none")]
    pub insecure_skip_tls: Option<bool>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
}

impl AddonPeriodHelmSource {
    pub fn new() -> AddonPeriodHelmSource {
        AddonPeriodHelmSource {
            insecure_skip_tls: None,
            password: None,
            url: None,
            username: None,
        }
    }
}


