/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddonPeriodDeployTo {
    #[serde(rename = "disableControlPlane")]
    pub disable_control_plane: bool,
    #[serde(rename = "runtimeCluster")]
    pub runtime_cluster: bool,
}

impl AddonPeriodDeployTo {
    pub fn new(disable_control_plane: bool, runtime_cluster: bool) -> AddonPeriodDeployTo {
        AddonPeriodDeployTo {
            disable_control_plane,
            runtime_cluster,
        }
    }
}


