/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddonPeriodOssAddonSource {
    #[serde(rename = "bucket")]
    pub bucket: String,
    #[serde(rename = "end_point")]
    pub end_point: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl AddonPeriodOssAddonSource {
    pub fn new(bucket: String, end_point: String, path: String) -> AddonPeriodOssAddonSource {
        AddonPeriodOssAddonSource {
            bucket,
            end_point,
            path,
        }
    }
}


