/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonPeriodKubeParameter {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "fieldPaths")]
    pub field_paths: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CommonPeriodKubeParameter {
    pub fn new(field_paths: Vec<String>, name: String, r#type: String) -> CommonPeriodKubeParameter {
        CommonPeriodKubeParameter {
            description: None,
            field_paths,
            name,
            required: None,
            r#type,
        }
    }
}


