/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonPeriodWorkloadTypeDescriptor {
    #[serde(rename = "definition", skip_serializing_if = "Option::is_none")]
    pub definition: Option<Box<crate::models::CommonPeriodWorkloadGvk>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl CommonPeriodWorkloadTypeDescriptor {
    pub fn new() -> CommonPeriodWorkloadTypeDescriptor {
        CommonPeriodWorkloadTypeDescriptor {
            definition: None,
            r#type: None,
        }
    }
}


