/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonPeriodSchematic {
    #[serde(rename = "cue", skip_serializing_if = "Option::is_none")]
    pub cue: Option<Box<crate::models::CommonPeriodCue>>,
    #[serde(rename = "helm", skip_serializing_if = "Option::is_none")]
    pub helm: Option<Box<crate::models::CommonPeriodHelm>>,
    #[serde(rename = "kube", skip_serializing_if = "Option::is_none")]
    pub kube: Option<Box<crate::models::CommonPeriodKube>>,
    #[serde(rename = "terraform", skip_serializing_if = "Option::is_none")]
    pub terraform: Option<Box<crate::models::CommonPeriodTerraform>>,
}

impl CommonPeriodSchematic {
    pub fn new() -> CommonPeriodSchematic {
        CommonPeriodSchematic {
            cue: None,
            helm: None,
            kube: None,
            terraform: None,
        }
    }
}


