/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonPeriodApplicationTraitStatus {
    #[serde(rename = "healthy")]
    pub healthy: bool,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CommonPeriodApplicationTraitStatus {
    pub fn new(healthy: bool, r#type: String) -> CommonPeriodApplicationTraitStatus {
        CommonPeriodApplicationTraitStatus {
            healthy,
            message: None,
            r#type,
        }
    }
}


