/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonPeriodCue {
    #[serde(rename = "template")]
    pub template: String,
}

impl CommonPeriodCue {
    pub fn new(template: String) -> CommonPeriodCue {
        CommonPeriodCue {
            template,
        }
    }
}


