/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonPeriodHelm {
    #[serde(rename = "release")]
    pub release: String,
    #[serde(rename = "repository")]
    pub repository: String,
}

impl CommonPeriodHelm {
    pub fn new(release: String, repository: String) -> CommonPeriodHelm {
        CommonPeriodHelm {
            release,
            repository,
        }
    }
}


