/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommonPeriodRevision {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "revision")]
    pub revision: i64,
    #[serde(rename = "revisionHash", skip_serializing_if = "Option::is_none")]
    pub revision_hash: Option<String>,
}

impl CommonPeriodRevision {
    pub fn new(name: String, revision: i64) -> CommonPeriodRevision {
        CommonPeriodRevision {
            name,
            revision,
            revision_hash: None,
        }
    }
}


