/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConditionPeriodCondition {
    #[serde(rename = "lastTransitionTime")]
    pub last_transition_time: String,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ConditionPeriodCondition {
    pub fn new(last_transition_time: String, reason: String, status: String, r#type: String) -> ConditionPeriodCondition {
        ConditionPeriodCondition {
            last_transition_time,
            message: None,
            reason,
            status,
            r#type,
        }
    }
}


