/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigPeriodDistribution {
    #[serde(rename = "application")]
    pub application: Box<crate::models::TypesPeriodNamespacedName>,
    #[serde(rename = "configs")]
    pub configs: Vec<crate::models::ConfigPeriodNamespacedName>,
    #[serde(rename = "createdTime")]
    pub created_time: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "status")]
    pub status: Box<crate::models::CommonPeriodAppStatus>,
    #[serde(rename = "targets")]
    pub targets: Vec<crate::models::ConfigPeriodClusterTarget>,
}

impl ConfigPeriodDistribution {
    pub fn new(application: crate::models::TypesPeriodNamespacedName, configs: Vec<crate::models::ConfigPeriodNamespacedName>, created_time: String, name: String, namespace: String, status: crate::models::CommonPeriodAppStatus, targets: Vec<crate::models::ConfigPeriodClusterTarget>) -> ConfigPeriodDistribution {
        ConfigPeriodDistribution {
            application: Box::new(application),
            configs,
            created_time,
            name,
            namespace,
            status: Box::new(status),
            targets,
        }
    }
}


