/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigPeriodClusterTargetStatus {
    #[serde(rename = "application")]
    pub application: Box<crate::models::ConfigPeriodNamespacedName>,
    #[serde(rename = "clusterName")]
    pub cluster_name: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "status")]
    pub status: String,
}

impl ConfigPeriodClusterTargetStatus {
    pub fn new(application: crate::models::ConfigPeriodNamespacedName, cluster_name: String, message: String, namespace: String, status: String) -> ConfigPeriodClusterTargetStatus {
        ConfigPeriodClusterTargetStatus {
            application: Box::new(application),
            cluster_name,
            message,
            namespace,
            status,
        }
    }
}


