/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelPeriodImageRepository {
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    #[serde(rename = "fullName")]
    pub full_name: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ModelPeriodImageRepository {
    pub fn new(full_name: String, name: String, namespace: String, r#type: String) -> ModelPeriodImageRepository {
        ModelPeriodImageRepository {
            create_time: None,
            full_name,
            name,
            namespace,
            region: None,
            r#type,
        }
    }
}


