/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelPeriodWorkflowSpec {
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Box<crate::models::V1alpha1PeriodWorkflowExecuteMode>>,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<crate::models::ModelPeriodWorkflowStep>>,
}

impl ModelPeriodWorkflowSpec {
    pub fn new() -> ModelPeriodWorkflowSpec {
        ModelPeriodWorkflowSpec {
            mode: None,
            steps: None,
        }
    }
}


