/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ModelPeriodBaseModel {
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "updateTime")]
    pub update_time: String,
}

impl ModelPeriodBaseModel {
    pub fn new(create_time: String, update_time: String) -> ModelPeriodBaseModel {
        ModelPeriodBaseModel {
            create_time,
            update_time,
        }
    }
}


