/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelPeriodApplicationTrait {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<serde_json::Value>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "updateTime")]
    pub update_time: String,
}

impl ModelPeriodApplicationTrait {
    pub fn new(alias: String, create_time: String, description: String, r#type: String, update_time: String) -> ModelPeriodApplicationTrait {
        ModelPeriodApplicationTrait {
            alias,
            create_time,
            description,
            properties: None,
            r#type,
            update_time,
        }
    }
}


