/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelPeriodProjectRef {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "roles")]
    pub roles: Vec<String>,
}

impl ModelPeriodProjectRef {
    pub fn new(name: String, roles: Vec<String>) -> ModelPeriodProjectRef {
        ModelPeriodProjectRef {
            name,
            roles,
        }
    }
}


