/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchemaPeriodGroupOption {
    #[serde(rename = "keys")]
    pub keys: Vec<String>,
    #[serde(rename = "label")]
    pub label: String,
}

impl SchemaPeriodGroupOption {
    pub fn new(keys: Vec<String>, label: String) -> SchemaPeriodGroupOption {
        SchemaPeriodGroupOption {
            keys,
            label,
        }
    }
}


