/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SchemaPeriodOption {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "value")]
    pub value: serde_json::Value,
}

impl SchemaPeriodOption {
    pub fn new(label: String, value: serde_json::Value) -> SchemaPeriodOption {
        SchemaPeriodOption {
            label,
            value,
        }
    }
}


