/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TypesPeriodNamespacedName {
    #[serde(rename = "Name")]
    pub name: String,
    #[serde(rename = "Namespace")]
    pub namespace: String,
}

impl TypesPeriodNamespacedName {
    pub fn new(name: String, namespace: String) -> TypesPeriodNamespacedName {
        TypesPeriodNamespacedName {
            name,
            namespace,
        }
    }
}


