/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TypesPeriodRequirement {
    #[serde(rename = "velauxVersion")]
    pub velaux_version: String,
}

impl TypesPeriodRequirement {
    pub fn new(velaux_version: String) -> TypesPeriodRequirement {
        TypesPeriodRequirement {
            velaux_version,
        }
    }
}


