/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TypesPeriodScreenshots {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path")]
    pub path: String,
}

impl TypesPeriodScreenshots {
    pub fn new(name: String, path: String) -> TypesPeriodScreenshots {
        TypesPeriodScreenshots {
            name,
            path,
        }
    }
}


