/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodCreateClusterNamespaceRequest {
    #[serde(rename = "namespace")]
    pub namespace: String,
}

impl V1PeriodCreateClusterNamespaceRequest {
    pub fn new(namespace: String) -> V1PeriodCreateClusterNamespaceRequest {
        V1PeriodCreateClusterNamespaceRequest {
            namespace,
        }
    }
}


