/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodDexConfigResponse {
    #[serde(rename = "clientID")]
    pub client_id: String,
    #[serde(rename = "clientSecret")]
    pub client_secret: String,
    #[serde(rename = "issuer")]
    pub issuer: String,
    #[serde(rename = "redirectURL")]
    pub redirect_url: String,
}

impl V1PeriodDexConfigResponse {
    pub fn new(client_id: String, client_secret: String, issuer: String, redirect_url: String) -> V1PeriodDexConfigResponse {
        V1PeriodDexConfigResponse {
            client_id,
            client_secret,
            issuer,
            redirect_url,
        }
    }
}


