/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodDetailPolicyResponse {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "creator")]
    pub creator: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "envName")]
    pub env_name: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "properties")]
    pub properties: serde_json::Value,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "updateTime")]
    pub update_time: String,
    #[serde(rename = "workflowPolicyBind", skip_serializing_if = "Option::is_none")]
    pub workflow_policy_bind: Option<Vec<crate::models::V1PeriodWorkflowPolicyBinding>>,
}

impl V1PeriodDetailPolicyResponse {
    pub fn new(alias: String, create_time: String, creator: String, description: String, env_name: String, name: String, properties: serde_json::Value, r#type: String, update_time: String) -> V1PeriodDetailPolicyResponse {
        V1PeriodDetailPolicyResponse {
            alias,
            create_time,
            creator,
            description,
            env_name,
            name,
            properties,
            r#type,
            update_time,
            workflow_policy_bind: None,
        }
    }
}


