/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodCreateApplicationTriggerRequest {
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "componentName", skip_serializing_if = "Option::is_none")]
    pub component_name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "payloadType")]
    pub payload_type: String,
    #[serde(rename = "registry", skip_serializing_if = "Option::is_none")]
    pub registry: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "workflowName")]
    pub workflow_name: String,
}

impl V1PeriodCreateApplicationTriggerRequest {
    pub fn new(name: String, payload_type: String, r#type: String, workflow_name: String) -> V1PeriodCreateApplicationTriggerRequest {
        V1PeriodCreateApplicationTriggerRequest {
            alias: None,
            component_name: None,
            description: None,
            name,
            payload_type,
            registry: None,
            r#type,
            workflow_name,
        }
    }
}


