/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodListProjectUsersResponse {
    #[serde(rename = "total")]
    pub total: i64,
    #[serde(rename = "users")]
    pub users: Vec<crate::models::V1PeriodProjectUserBase>,
}

impl V1PeriodListProjectUsersResponse {
    pub fn new(total: i64, users: Vec<crate::models::V1PeriodProjectUserBase>) -> V1PeriodListProjectUsersResponse {
        V1PeriodListProjectUsersResponse {
            total,
            users,
        }
    }
}


