/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodCreateWorkflowRequest {
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "default")]
    pub default: bool,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "envName")]
    pub env_name: String,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<crate::models::V1PeriodWorkflowStep>>,
    #[serde(rename = "subMode")]
    pub sub_mode: String,
}

impl V1PeriodCreateWorkflowRequest {
    pub fn new(default: bool, env_name: String, mode: String, name: String, sub_mode: String) -> V1PeriodCreateWorkflowRequest {
        V1PeriodCreateWorkflowRequest {
            alias: None,
            default,
            description: None,
            env_name,
            mode,
            name,
            steps: None,
            sub_mode,
        }
    }
}


