/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodUpdateUiSchemaRequest {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "uiSchema")]
    pub ui_schema: Vec<crate::models::SchemaPeriodUiParameter>,
}

impl V1PeriodUpdateUiSchemaRequest {
    pub fn new(r#type: String, ui_schema: Vec<crate::models::SchemaPeriodUiParameter>) -> V1PeriodUpdateUiSchemaRequest {
        V1PeriodUpdateUiSchemaRequest {
            r#type,
            ui_schema,
        }
    }
}


