/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodListConfigResponse {
    #[serde(rename = "configs")]
    pub configs: Vec<crate::models::V1PeriodConfig>,
}

impl V1PeriodListConfigResponse {
    pub fn new(configs: Vec<crate::models::V1PeriodConfig>) -> V1PeriodListConfigResponse {
        V1PeriodListConfigResponse {
            configs,
        }
    }
}


