/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodManagedPluginDto {
    #[serde(rename = "authSecret", skip_serializing_if = "Option::is_none")]
    pub auth_secret: Option<Box<crate::models::TypesPeriodKubernetesSecret>>,
    #[serde(rename = "authType", skip_serializing_if = "Option::is_none")]
    pub auth_type: Option<String>,
    #[serde(rename = "backend")]
    pub backend: bool,
    #[serde(rename = "backendService")]
    pub backend_service: Box<crate::models::TypesPeriodKubernetesService>,
    #[serde(rename = "backendType")]
    pub backend_type: String,
    #[serde(rename = "baseURL")]
    pub base_url: String,
    #[serde(rename = "category")]
    pub category: String,
    #[serde(rename = "class")]
    pub class: String,
    #[serde(rename = "defaultNavURL")]
    pub default_nav_url: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "includes")]
    pub includes: Vec<crate::models::TypesPeriodIncludes>,
    #[serde(rename = "info")]
    pub info: Box<crate::models::TypesPeriodInfo>,
    #[serde(rename = "jsonSetting")]
    pub json_setting: serde_json::Value,
    #[serde(rename = "kubePermissions", skip_serializing_if = "Option::is_none")]
    pub kube_permissions: Option<Vec<crate::models::V1PeriodPolicyRule>>,
    #[serde(rename = "module")]
    pub module: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "proxy")]
    pub proxy: bool,
    #[serde(rename = "requirement", skip_serializing_if = "Option::is_none")]
    pub requirement: Option<Box<crate::models::TypesPeriodRequirement>>,
    #[serde(rename = "routes", skip_serializing_if = "Option::is_none")]
    pub routes: Option<Vec<crate::models::TypesPeriodRoute>>,
    #[serde(rename = "secureJsonFields")]
    pub secure_json_fields: ::std::collections::HashMap<String, bool>,
    #[serde(rename = "subType")]
    pub sub_type: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl V1PeriodManagedPluginDto {
    pub fn new(backend: bool, backend_service: crate::models::TypesPeriodKubernetesService, backend_type: String, base_url: String, category: String, class: String, default_nav_url: String, enabled: bool, id: String, includes: Vec<crate::models::TypesPeriodIncludes>, info: crate::models::TypesPeriodInfo, json_setting: serde_json::Value, module: String, name: String, proxy: bool, secure_json_fields: ::std::collections::HashMap<String, bool>, sub_type: String, r#type: String) -> V1PeriodManagedPluginDto {
        V1PeriodManagedPluginDto {
            auth_secret: None,
            auth_type: None,
            backend,
            backend_service: Box::new(backend_service),
            backend_type,
            base_url,
            category,
            class,
            default_nav_url,
            enabled,
            id,
            includes,
            info: Box::new(info),
            json_setting,
            kube_permissions: None,
            module,
            name,
            proxy,
            requirement: None,
            routes: None,
            secure_json_fields,
            sub_type,
            r#type,
        }
    }
}


