/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodApplicationStatisticsResponse {
    #[serde(rename = "envCount")]
    pub env_count: i64,
    #[serde(rename = "revisionCount")]
    pub revision_count: i64,
    #[serde(rename = "targetCount")]
    pub target_count: i64,
    #[serde(rename = "workflowCount")]
    pub workflow_count: i64,
}

impl V1PeriodApplicationStatisticsResponse {
    pub fn new(env_count: i64, revision_count: i64, target_count: i64, workflow_count: i64) -> V1PeriodApplicationStatisticsResponse {
        V1PeriodApplicationStatisticsResponse {
            env_count,
            revision_count,
            target_count,
            workflow_count,
        }
    }
}


