/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodAddonBaseStatus {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "phase")]
    pub phase: String,
}

impl V1PeriodAddonBaseStatus {
    pub fn new(name: String, phase: String) -> V1PeriodAddonBaseStatus {
        V1PeriodAddonBaseStatus {
            name,
            phase,
        }
    }
}


