/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodContextNameResponse {
    #[serde(rename = "name")]
    pub name: String,
}

impl V1PeriodContextNameResponse {
    pub fn new(name: String) -> V1PeriodContextNameResponse {
        V1PeriodContextNameResponse {
            name,
        }
    }
}


