/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodCreateAddonRegistryRequest {
    #[serde(rename = "git", skip_serializing_if = "Option::is_none")]
    pub git: Option<Box<crate::models::AddonPeriodGitAddonSource>>,
    #[serde(rename = "gitee", skip_serializing_if = "Option::is_none")]
    pub gitee: Option<Box<crate::models::AddonPeriodGiteeAddonSource>>,
    #[serde(rename = "gitlab", skip_serializing_if = "Option::is_none")]
    pub gitlab: Option<Box<crate::models::AddonPeriodGitlabAddonSource>>,
    #[serde(rename = "helm", skip_serializing_if = "Option::is_none")]
    pub helm: Option<Box<crate::models::AddonPeriodHelmSource>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "oss", skip_serializing_if = "Option::is_none")]
    pub oss: Option<Box<crate::models::AddonPeriodOssAddonSource>>,
}

impl V1PeriodCreateAddonRegistryRequest {
    pub fn new(name: String) -> V1PeriodCreateAddonRegistryRequest {
        V1PeriodCreateAddonRegistryRequest {
            git: None,
            gitee: None,
            gitlab: None,
            helm: None,
            name,
            oss: None,
        }
    }
}


