/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodApplicationResponse {
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "spec")]
    pub spec: Box<crate::models::V1beta1PeriodApplicationSpec>,
    #[serde(rename = "status")]
    pub status: Box<crate::models::CommonPeriodAppStatus>,
}

impl V1PeriodApplicationResponse {
    pub fn new(api_version: String, kind: String, spec: crate::models::V1beta1PeriodApplicationSpec, status: crate::models::CommonPeriodAppStatus) -> V1PeriodApplicationResponse {
        V1PeriodApplicationResponse {
            api_version,
            kind,
            spec: Box::new(spec),
            status: Box::new(status),
        }
    }
}


