/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodListWorkflowResponse {
    #[serde(rename = "workflows")]
    pub workflows: Vec<crate::models::V1PeriodWorkflowBase>,
}

impl V1PeriodListWorkflowResponse {
    pub fn new(workflows: Vec<crate::models::V1PeriodWorkflowBase>) -> V1PeriodListWorkflowResponse {
        V1PeriodListWorkflowResponse {
            workflows,
        }
    }
}


