/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodPipelineBase {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "project")]
    pub project: Box<crate::models::V1PeriodNameAlias>,
    #[serde(rename = "spec")]
    pub spec: Box<crate::models::ModelPeriodWorkflowSpec>,
}

impl V1PeriodPipelineBase {
    pub fn new(alias: String, create_time: String, description: String, name: String, project: crate::models::V1PeriodNameAlias, spec: crate::models::ModelPeriodWorkflowSpec) -> V1PeriodPipelineBase {
        V1PeriodPipelineBase {
            alias,
            create_time,
            description,
            name,
            project: Box::new(project),
            spec: Box::new(spec),
        }
    }
}


