/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodListPipelineResponse {
    #[serde(rename = "pipelines")]
    pub pipelines: Vec<crate::models::V1PeriodPipelineListItem>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl V1PeriodListPipelineResponse {
    pub fn new(pipelines: Vec<crate::models::V1PeriodPipelineListItem>, total: i32) -> V1PeriodListPipelineResponse {
        V1PeriodListPipelineResponse {
            pipelines,
            total,
        }
    }
}


