/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodGetLoginTypeResponse {
    #[serde(rename = "loginType")]
    pub login_type: String,
}

impl V1PeriodGetLoginTypeResponse {
    pub fn new(login_type: String) -> V1PeriodGetLoginTypeResponse {
        V1PeriodGetLoginTypeResponse {
            login_type,
        }
    }
}


