/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodLoginUserInfoResponse {
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "disabled")]
    pub disabled: bool,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "lastLoginTime")]
    pub last_login_time: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "platformPermissions")]
    pub platform_permissions: Vec<crate::models::V1PeriodPermissionBase>,
    #[serde(rename = "projectPermissions")]
    pub project_permissions: ::std::collections::HashMap<String, Vec<crate::models::V1PeriodPermissionBase>>,
    #[serde(rename = "projects")]
    pub projects: Vec<crate::models::V1PeriodProjectBase>,
}

impl V1PeriodLoginUserInfoResponse {
    pub fn new(create_time: String, disabled: bool, email: String, last_login_time: String, name: String, platform_permissions: Vec<crate::models::V1PeriodPermissionBase>, project_permissions: ::std::collections::HashMap<String, Vec<crate::models::V1PeriodPermissionBase>>, projects: Vec<crate::models::V1PeriodProjectBase>) -> V1PeriodLoginUserInfoResponse {
        V1PeriodLoginUserInfoResponse {
            alias: None,
            create_time,
            disabled,
            email,
            last_login_time,
            name,
            platform_permissions,
            project_permissions,
            projects,
        }
    }
}


