/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodTerraformProvider {
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "region")]
    pub region: String,
}

impl V1PeriodTerraformProvider {
    pub fn new(create_time: String, name: String, provider: String, region: String) -> V1PeriodTerraformProvider {
        V1PeriodTerraformProvider {
            create_time,
            name,
            provider,
            region,
        }
    }
}


