/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodCreateConfigDistributionRequest {
    #[serde(rename = "configs")]
    pub configs: Vec<crate::models::V1PeriodNamespacedName>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "targets")]
    pub targets: Vec<crate::models::V1PeriodClusterTarget>,
}

impl V1PeriodCreateConfigDistributionRequest {
    pub fn new(configs: Vec<crate::models::V1PeriodNamespacedName>, name: String, targets: Vec<crate::models::V1PeriodClusterTarget>) -> V1PeriodCreateConfigDistributionRequest {
        V1PeriodCreateConfigDistributionRequest {
            configs,
            name,
            targets,
        }
    }
}


