/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodPipelineRun {
    #[serde(rename = "contextName")]
    pub context_name: String,
    #[serde(rename = "contextValues")]
    pub context_values: Vec<crate::models::ModelPeriodValue>,
    #[serde(rename = "pipelineName")]
    pub pipeline_name: String,
    #[serde(rename = "pipelineRunName")]
    pub pipeline_run_name: String,
    #[serde(rename = "project")]
    pub project: Box<crate::models::V1PeriodNameAlias>,
    #[serde(rename = "record")]
    pub record: i64,
    #[serde(rename = "spec")]
    pub spec: Box<crate::models::V1alpha1PeriodWorkflowRunSpec>,
    #[serde(rename = "status")]
    pub status: Box<crate::models::V1alpha1PeriodWorkflowRunStatus>,
}

impl V1PeriodPipelineRun {
    pub fn new(context_name: String, context_values: Vec<crate::models::ModelPeriodValue>, pipeline_name: String, pipeline_run_name: String, project: crate::models::V1PeriodNameAlias, record: i64, spec: crate::models::V1alpha1PeriodWorkflowRunSpec, status: crate::models::V1alpha1PeriodWorkflowRunStatus) -> V1PeriodPipelineRun {
        V1PeriodPipelineRun {
            context_name,
            context_values,
            pipeline_name,
            pipeline_run_name,
            project: Box::new(project),
            record,
            spec: Box::new(spec),
            status: Box::new(status),
        }
    }
}


