/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodSystemInfoRequest {
    #[serde(rename = "dexUserDefaultProjects", skip_serializing_if = "Option::is_none")]
    pub dex_user_default_projects: Option<Vec<crate::models::ModelPeriodProjectRef>>,
    #[serde(rename = "enableCollection")]
    pub enable_collection: bool,
    #[serde(rename = "loginType")]
    pub login_type: String,
    #[serde(rename = "velaAddress", skip_serializing_if = "Option::is_none")]
    pub vela_address: Option<String>,
}

impl V1PeriodSystemInfoRequest {
    pub fn new(enable_collection: bool, login_type: String) -> V1PeriodSystemInfoRequest {
        V1PeriodSystemInfoRequest {
            dex_user_default_projects: None,
            enable_collection,
            login_type,
            vela_address: None,
        }
    }
}


