/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodCreatePermissionRequest {
    #[serde(rename = "actions")]
    pub actions: Vec<String>,
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "effect")]
    pub effect: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "resources")]
    pub resources: Vec<String>,
}

impl V1PeriodCreatePermissionRequest {
    pub fn new(actions: Vec<String>, alias: String, effect: String, name: String, resources: Vec<String>) -> V1PeriodCreatePermissionRequest {
        V1PeriodCreatePermissionRequest {
            actions,
            alias,
            effect,
            name,
            resources,
        }
    }
}


