/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodUpdateRoleRequest {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "permissions")]
    pub permissions: Vec<String>,
}

impl V1PeriodUpdateRoleRequest {
    pub fn new(alias: String, permissions: Vec<String>) -> V1PeriodUpdateRoleRequest {
        V1PeriodUpdateRoleRequest {
            alias,
            permissions,
        }
    }
}


