/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodListEnabledAddonResponse {
    #[serde(rename = "enabledAddons")]
    pub enabled_addons: Vec<crate::models::V1PeriodAddonBaseStatus>,
}

impl V1PeriodListEnabledAddonResponse {
    pub fn new(enabled_addons: Vec<crate::models::V1PeriodAddonBaseStatus>) -> V1PeriodListEnabledAddonResponse {
        V1PeriodListEnabledAddonResponse {
            enabled_addons,
        }
    }
}


