/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodNameAlias {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl V1PeriodNameAlias {
    pub fn new(alias: String, name: String) -> V1PeriodNameAlias {
        V1PeriodNameAlias {
            alias,
            name,
        }
    }
}


