/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodCreateCloudClusterRequest {
    #[serde(rename = "accessKeyID")]
    pub access_key_id: String,
    #[serde(rename = "accessKeySecret")]
    pub access_key_secret: String,
    #[serde(rename = "cpuCoresPerWorker")]
    pub cpu_cores_per_worker: i64,
    #[serde(rename = "memoryPerWorker")]
    pub memory_per_worker: i64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "workerNumber")]
    pub worker_number: i32,
    #[serde(rename = "zone")]
    pub zone: String,
}

impl V1PeriodCreateCloudClusterRequest {
    pub fn new(access_key_id: String, access_key_secret: String, cpu_cores_per_worker: i64, memory_per_worker: i64, name: String, worker_number: i32, zone: String) -> V1PeriodCreateCloudClusterRequest {
        V1PeriodCreateCloudClusterRequest {
            access_key_id,
            access_key_secret,
            cpu_cores_per_worker,
            memory_per_worker,
            name,
            worker_number,
            zone,
        }
    }
}


