/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodAddProjectUserRequest {
    #[serde(rename = "userName")]
    pub user_name: String,
    #[serde(rename = "userRoles")]
    pub user_roles: Vec<String>,
}

impl V1PeriodAddProjectUserRequest {
    pub fn new(user_name: String, user_roles: Vec<String>) -> V1PeriodAddProjectUserRequest {
        V1PeriodAddProjectUserRequest {
            user_name,
            user_roles,
        }
    }
}


