/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodAppDryRunReq {
    #[serde(rename = "dryRunType")]
    pub dry_run_type: String,
    #[serde(rename = "env")]
    pub env: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "workflow")]
    pub workflow: String,
}

impl V1PeriodAppDryRunReq {
    pub fn new(dry_run_type: String, env: String, version: String, workflow: String) -> V1PeriodAppDryRunReq {
        V1PeriodAppDryRunReq {
            dry_run_type,
            env,
            version,
            workflow,
        }
    }
}


