/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodCreateContextValuesRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "values")]
    pub values: Vec<crate::models::ModelPeriodValue>,
}

impl V1PeriodCreateContextValuesRequest {
    pub fn new(name: String, values: Vec<crate::models::ModelPeriodValue>) -> V1PeriodCreateContextValuesRequest {
        V1PeriodCreateContextValuesRequest {
            name,
            values,
        }
    }
}


