/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodListPipelineRunResponse {
    #[serde(rename = "runs")]
    pub runs: Vec<crate::models::V1PeriodPipelineRunBriefing>,
    #[serde(rename = "total")]
    pub total: i64,
}

impl V1PeriodListPipelineRunResponse {
    pub fn new(runs: Vec<crate::models::V1PeriodPipelineRunBriefing>, total: i64) -> V1PeriodListPipelineRunResponse {
        V1PeriodListPipelineRunResponse {
            runs,
            total,
        }
    }
}


