/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodApplicationTemplateBase {
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "templateName")]
    pub template_name: String,
    #[serde(rename = "updateTime")]
    pub update_time: String,
    #[serde(rename = "versions", skip_serializing_if = "Option::is_none")]
    pub versions: Option<Vec<crate::models::V1PeriodApplicationTemplateVersion>>,
}

impl V1PeriodApplicationTemplateBase {
    pub fn new(create_time: String, template_name: String, update_time: String) -> V1PeriodApplicationTemplateBase {
        V1PeriodApplicationTemplateBase {
            create_time,
            template_name,
            update_time,
            versions: None,
        }
    }
}


