/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodSimpleResponse {
    #[serde(rename = "status")]
    pub status: String,
}

impl V1PeriodSimpleResponse {
    pub fn new(status: String) -> V1PeriodSimpleResponse {
        V1PeriodSimpleResponse {
            status,
        }
    }
}


