/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodEnvBinding {
    #[serde(rename = "name")]
    pub name: String,
}

impl V1PeriodEnvBinding {
    pub fn new(name: String) -> V1PeriodEnvBinding {
        V1PeriodEnvBinding {
            name,
        }
    }
}


