/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodRootFs {
    #[serde(rename = "diff_ids")]
    pub diff_ids: Vec<crate::models::V1PeriodHash>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl V1PeriodRootFs {
    pub fn new(diff_ids: Vec<crate::models::V1PeriodHash>, r#type: String) -> V1PeriodRootFs {
        V1PeriodRootFs {
            diff_ids,
            r#type,
        }
    }
}


