/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodPipelineInfo {
    #[serde(rename = "lastRun")]
    pub last_run: Box<crate::models::V1PeriodPipelineRun>,
    #[serde(rename = "runStat")]
    pub run_stat: Box<crate::models::V1PeriodRunStat>,
}

impl V1PeriodPipelineInfo {
    pub fn new(last_run: crate::models::V1PeriodPipelineRun, run_stat: crate::models::V1PeriodRunStat) -> V1PeriodPipelineInfo {
        V1PeriodPipelineInfo {
            last_run: Box::new(last_run),
            run_stat: Box::new(run_stat),
        }
    }
}


