/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodCreatePipelineRequest {
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "spec")]
    pub spec: Box<crate::models::ModelPeriodWorkflowSpec>,
}

impl V1PeriodCreatePipelineRequest {
    pub fn new(name: String, spec: crate::models::ModelPeriodWorkflowSpec) -> V1PeriodCreatePipelineRequest {
        V1PeriodCreatePipelineRequest {
            alias: None,
            description: None,
            name,
            spec: Box::new(spec),
        }
    }
}


