/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodListDefinitionResponse {
    #[serde(rename = "definitions")]
    pub definitions: Vec<crate::models::V1PeriodDefinitionBase>,
}

impl V1PeriodListDefinitionResponse {
    pub fn new(definitions: Vec<crate::models::V1PeriodDefinitionBase>) -> V1PeriodListDefinitionResponse {
        V1PeriodListDefinitionResponse {
            definitions,
        }
    }
}


