/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodApplicationResourceInfo {
    #[serde(rename = "componentNum")]
    pub component_num: i64,
}

impl V1PeriodApplicationResourceInfo {
    pub fn new(component_num: i64) -> V1PeriodApplicationResourceInfo {
        V1PeriodApplicationResourceInfo {
            component_num,
        }
    }
}


