/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodListApplicationPolicy {
    #[serde(rename = "policies")]
    pub policies: Vec<crate::models::V1PeriodPolicyBase>,
}

impl V1PeriodListApplicationPolicy {
    pub fn new(policies: Vec<crate::models::V1PeriodPolicyBase>) -> V1PeriodListApplicationPolicy {
        V1PeriodListApplicationPolicy {
            policies,
        }
    }
}


