/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodGetPipelineRunInputResponse {
    #[serde(rename = "inputs")]
    pub inputs: Vec<crate::models::V1PeriodStepInputBase>,
}

impl V1PeriodGetPipelineRunInputResponse {
    pub fn new(inputs: Vec<crate::models::V1PeriodStepInputBase>) -> V1PeriodGetPipelineRunInputResponse {
        V1PeriodGetPipelineRunInputResponse {
            inputs,
        }
    }
}


