/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodCreateApplicationTraitRequest {
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "properties")]
    pub properties: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl V1PeriodCreateApplicationTraitRequest {
    pub fn new(properties: String, r#type: String) -> V1PeriodCreateApplicationTraitRequest {
        V1PeriodCreateApplicationTraitRequest {
            alias: None,
            description: None,
            properties,
            r#type,
        }
    }
}


