/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodUserProjectBase {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "joinTime")]
    pub join_time: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<crate::models::V1PeriodNameAlias>>,
    #[serde(rename = "roles")]
    pub roles: Vec<crate::models::V1PeriodNameAlias>,
}

impl V1PeriodUserProjectBase {
    pub fn new(alias: String, description: String, join_time: String, name: String, roles: Vec<crate::models::V1PeriodNameAlias>) -> V1PeriodUserProjectBase {
        V1PeriodUserProjectBase {
            alias,
            description,
            join_time,
            name,
            owner: None,
            roles,
        }
    }
}


