/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodEnablingProgress {
    #[serde(rename = "enabled_components")]
    pub enabled_components: i32,
    #[serde(rename = "total_components")]
    pub total_components: i32,
}

impl V1PeriodEnablingProgress {
    pub fn new(enabled_components: i32, total_components: i32) -> V1PeriodEnablingProgress {
        V1PeriodEnablingProgress {
            enabled_components,
            total_components,
        }
    }
}


