/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodGetPipelineResponse {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "info")]
    pub info: Box<crate::models::V1PeriodPipelineInfo>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "project")]
    pub project: Box<crate::models::V1PeriodNameAlias>,
    #[serde(rename = "spec")]
    pub spec: Box<crate::models::ModelPeriodWorkflowSpec>,
}

impl V1PeriodGetPipelineResponse {
    pub fn new(alias: String, create_time: String, description: String, info: crate::models::V1PeriodPipelineInfo, name: String, project: crate::models::V1PeriodNameAlias, spec: crate::models::ModelPeriodWorkflowSpec) -> V1PeriodGetPipelineResponse {
        V1PeriodGetPipelineResponse {
            alias,
            create_time,
            description,
            info: Box::new(info),
            name,
            project: Box::new(project),
            spec: Box::new(spec),
        }
    }
}


