/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodStepOutputBase {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "phase")]
    pub phase: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "values")]
    pub values: Vec<crate::models::V1PeriodOutputVar>,
}

impl V1PeriodStepOutputBase {
    pub fn new(id: String, name: String, phase: String, r#type: String, values: Vec<crate::models::V1PeriodOutputVar>) -> V1PeriodStepOutputBase {
        V1PeriodStepOutputBase {
            id,
            name,
            phase,
            r#type,
            values,
        }
    }
}


