/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodApplicationStatusListResponse {
    #[serde(rename = "status")]
    pub status: Vec<crate::models::V1PeriodApplicationStatusResponse>,
}

impl V1PeriodApplicationStatusListResponse {
    pub fn new(status: Vec<crate::models::V1PeriodApplicationStatusResponse>) -> V1PeriodApplicationStatusListResponse {
        V1PeriodApplicationStatusListResponse {
            status,
        }
    }
}


