/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodListTerraformProviderResponse {
    #[serde(rename = "providers")]
    pub providers: Vec<crate::models::V1PeriodTerraformProvider>,
}

impl V1PeriodListTerraformProviderResponse {
    pub fn new(providers: Vec<crate::models::V1PeriodTerraformProvider>) -> V1PeriodListTerraformProviderResponse {
        V1PeriodListTerraformProviderResponse {
            providers,
        }
    }
}


