/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodListClusterResponse {
    #[serde(rename = "clusters")]
    pub clusters: Vec<crate::models::V1PeriodClusterBase>,
    #[serde(rename = "total")]
    pub total: i64,
}

impl V1PeriodListClusterResponse {
    pub fn new(clusters: Vec<crate::models::V1PeriodClusterBase>, total: i64) -> V1PeriodListClusterResponse {
        V1PeriodListClusterResponse {
            clusters,
            total,
        }
    }
}


