/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodSystemInfoResponse {
    #[serde(rename = "dexUserDefaultPlatformRoles", skip_serializing_if = "Option::is_none")]
    pub dex_user_default_platform_roles: Option<Vec<String>>,
    #[serde(rename = "dexUserDefaultProjects", skip_serializing_if = "Option::is_none")]
    pub dex_user_default_projects: Option<Vec<crate::models::ModelPeriodProjectRef>>,
    #[serde(rename = "enableCollection")]
    pub enable_collection: bool,
    #[serde(rename = "installTime", skip_serializing_if = "Option::is_none")]
    pub install_time: Option<String>,
    #[serde(rename = "loginType")]
    pub login_type: String,
    #[serde(rename = "platformID")]
    pub platform_id: String,
    #[serde(rename = "statisticInfo", skip_serializing_if = "Option::is_none")]
    pub statistic_info: Option<Box<crate::models::V1PeriodStatisticInfo>>,
    #[serde(rename = "systemVersion")]
    pub system_version: Box<crate::models::V1PeriodSystemVersion>,
}

impl V1PeriodSystemInfoResponse {
    pub fn new(enable_collection: bool, login_type: String, platform_id: String, system_version: crate::models::V1PeriodSystemVersion) -> V1PeriodSystemInfoResponse {
        V1PeriodSystemInfoResponse {
            dex_user_default_platform_roles: None,
            dex_user_default_projects: None,
            enable_collection,
            install_time: None,
            login_type,
            platform_id,
            statistic_info: None,
            system_version: Box::new(system_version),
        }
    }
}


