/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodEnv {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "project")]
    pub project: Box<crate::models::V1PeriodNameAlias>,
    #[serde(rename = "targets", skip_serializing_if = "Option::is_none")]
    pub targets: Option<Vec<crate::models::V1PeriodNameAlias>>,
    #[serde(rename = "updateTime")]
    pub update_time: String,
}

impl V1PeriodEnv {
    pub fn new(alias: String, create_time: String, name: String, namespace: String, project: crate::models::V1PeriodNameAlias, update_time: String) -> V1PeriodEnv {
        V1PeriodEnv {
            alias,
            create_time,
            description: None,
            name,
            namespace,
            project: Box::new(project),
            targets: None,
            update_time,
        }
    }
}


