/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodListAddonRegistryResponse {
    #[serde(rename = "registries")]
    pub registries: Vec<crate::models::V1PeriodAddonRegistry>,
}

impl V1PeriodListAddonRegistryResponse {
    pub fn new(registries: Vec<crate::models::V1PeriodAddonRegistry>) -> V1PeriodListAddonRegistryResponse {
        V1PeriodListAddonRegistryResponse {
            registries,
        }
    }
}


