/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodApplicationTrait {
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "properties")]
    pub properties: serde_json::Value,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "updateTime")]
    pub update_time: String,
}

impl V1PeriodApplicationTrait {
    pub fn new(create_time: String, properties: serde_json::Value, r#type: String, update_time: String) -> V1PeriodApplicationTrait {
        V1PeriodApplicationTrait {
            alias: None,
            create_time,
            description: None,
            properties,
            r#type,
            update_time,
        }
    }
}


