/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodRoleBase {
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "permissions")]
    pub permissions: Vec<crate::models::V1PeriodNameAlias>,
    #[serde(rename = "updateTime")]
    pub update_time: String,
}

impl V1PeriodRoleBase {
    pub fn new(create_time: String, name: String, permissions: Vec<crate::models::V1PeriodNameAlias>, update_time: String) -> V1PeriodRoleBase {
        V1PeriodRoleBase {
            alias: None,
            create_time,
            name,
            permissions,
            update_time,
        }
    }
}


