/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodDetailWorkflowResponse {
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "createTime")]
    pub create_time: String,
    #[serde(rename = "default")]
    pub default: bool,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "enable")]
    pub enable: bool,
    #[serde(rename = "envName")]
    pub env_name: String,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<crate::models::V1PeriodWorkflowStep>>,
    #[serde(rename = "subMode")]
    pub sub_mode: String,
    #[serde(rename = "updateTime")]
    pub update_time: String,
}

impl V1PeriodDetailWorkflowResponse {
    pub fn new(alias: String, create_time: String, default: bool, description: String, enable: bool, env_name: String, mode: String, name: String, sub_mode: String, update_time: String) -> V1PeriodDetailWorkflowResponse {
        V1PeriodDetailWorkflowResponse {
            alias,
            create_time,
            default,
            description,
            enable,
            env_name,
            mode,
            name,
            steps: None,
            sub_mode,
            update_time,
        }
    }
}


