/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodClusterResourceInfo {
    #[serde(rename = "cpuCapacity")]
    pub cpu_capacity: i64,
    #[serde(rename = "cpuUsed")]
    pub cpu_used: i64,
    #[serde(rename = "gpuCapacity", skip_serializing_if = "Option::is_none")]
    pub gpu_capacity: Option<i64>,
    #[serde(rename = "gpuUsed", skip_serializing_if = "Option::is_none")]
    pub gpu_used: Option<i64>,
    #[serde(rename = "masterNumber")]
    pub master_number: i32,
    #[serde(rename = "memoryCapacity")]
    pub memory_capacity: i64,
    #[serde(rename = "memoryUsed")]
    pub memory_used: i64,
    #[serde(rename = "podCapacity")]
    pub pod_capacity: i64,
    #[serde(rename = "podUsed")]
    pub pod_used: i64,
    #[serde(rename = "storageClassList", skip_serializing_if = "Option::is_none")]
    pub storage_class_list: Option<Vec<String>>,
    #[serde(rename = "workerNumber")]
    pub worker_number: i32,
}

impl V1PeriodClusterResourceInfo {
    pub fn new(cpu_capacity: i64, cpu_used: i64, master_number: i32, memory_capacity: i64, memory_used: i64, pod_capacity: i64, pod_used: i64, worker_number: i32) -> V1PeriodClusterResourceInfo {
        V1PeriodClusterResourceInfo {
            cpu_capacity,
            cpu_used,
            gpu_capacity: None,
            gpu_used: None,
            master_number,
            memory_capacity,
            memory_used,
            pod_capacity,
            pod_used,
            storage_class_list: None,
            worker_number,
        }
    }
}


