/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodClusterTarget {
    #[serde(rename = "clusterName")]
    pub cluster_name: String,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl V1PeriodClusterTarget {
    pub fn new(cluster_name: String) -> V1PeriodClusterTarget {
        V1PeriodClusterTarget {
            cluster_name,
            namespace: None,
        }
    }
}


