/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1PeriodUpdateWorkflowRequest {
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    #[serde(rename = "default")]
    pub default: bool,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "mode")]
    pub mode: String,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<crate::models::V1PeriodWorkflowStep>>,
    #[serde(rename = "subMode")]
    pub sub_mode: String,
}

impl V1PeriodUpdateWorkflowRequest {
    pub fn new(default: bool, mode: String, sub_mode: String) -> V1PeriodUpdateWorkflowRequest {
        V1PeriodUpdateWorkflowRequest {
            alias: None,
            default,
            description: None,
            mode,
            steps: None,
            sub_mode,
        }
    }
}


