/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PeriodListImageRegistryResponse {
    #[serde(rename = "registries")]
    pub registries: Vec<crate::models::V1PeriodImageRegistry>,
}

impl V1PeriodListImageRegistryResponse {
    pub fn new(registries: Vec<crate::models::V1PeriodImageRegistry>) -> V1PeriodListImageRegistryResponse {
        V1PeriodListImageRegistryResponse {
            registries,
        }
    }
}


