/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PeriodWorkflowExecuteMode {
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<String>,
    #[serde(rename = "subSteps", skip_serializing_if = "Option::is_none")]
    pub sub_steps: Option<String>,
}

impl V1alpha1PeriodWorkflowExecuteMode {
    pub fn new() -> V1alpha1PeriodWorkflowExecuteMode {
        V1alpha1PeriodWorkflowExecuteMode {
            steps: None,
            sub_steps: None,
        }
    }
}


