/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PeriodWorkflowRunSpec {
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Box<crate::models::V1alpha1PeriodWorkflowExecuteMode>>,
    #[serde(rename = "workflowRef", skip_serializing_if = "Option::is_none")]
    pub workflow_ref: Option<String>,
    #[serde(rename = "workflowSpec", skip_serializing_if = "Option::is_none")]
    pub workflow_spec: Option<Box<crate::models::V1alpha1PeriodWorkflowSpec>>,
}

impl V1alpha1PeriodWorkflowRunSpec {
    pub fn new() -> V1alpha1PeriodWorkflowRunSpec {
        V1alpha1PeriodWorkflowRunSpec {
            context: None,
            mode: None,
            workflow_ref: None,
            workflow_spec: None,
        }
    }
}


