/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.9.7
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1alpha1PeriodOutputItem {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "valueFrom")]
    pub value_from: String,
}

impl V1alpha1PeriodOutputItem {
    pub fn new(name: String, value_from: String) -> V1alpha1PeriodOutputItem {
        V1alpha1PeriodOutputItem {
            name,
            value_from,
        }
    }
}


