/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1alpha1PeriodWorkflowSpec {
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<Vec<crate::models::V1alpha1PeriodWorkflowStep>>,
}

impl V1alpha1PeriodWorkflowSpec {
    pub fn new() -> V1alpha1PeriodWorkflowSpec {
        V1alpha1PeriodWorkflowSpec {
            steps: None,
        }
    }
}


