/*
 * Kubevela api doc
 *
 * Kubevela api doc
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: feedback@mail.kubevela.io
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct V1beta1PeriodWorkflowStepDefinitionSpec {
    #[serde(rename = "definitionRef", skip_serializing_if = "Option::is_none")]
    pub definition_ref: Option<Box<crate::models::CommonPeriodDefinitionReference>>,
    #[serde(rename = "schematic", skip_serializing_if = "Option::is_none")]
    pub schematic: Option<Box<crate::models::CommonPeriodSchematic>>,
}

impl V1beta1PeriodWorkflowStepDefinitionSpec {
    pub fn new() -> V1beta1PeriodWorkflowStepDefinitionSpec {
        V1beta1PeriodWorkflowStepDefinitionSpec {
            definition_ref: None,
            schematic: None,
        }
    }
}


